import Head from 'next/head'
import '@/styles/globals.css'
import Navbar from '@/components/Navbar'
import Footers from '@/components/Footers'


export default function App({ Component, pageProps }) {
  return (
    <>
      {/* APP Layout */}
      <Head>
        <title>Learn Next JS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Component {...pageProps} />
      <Footers />
    </>
  )
}
